const companies=`
7203|トヨタ自動車|輸送用機器|https://global.toyota/jp/
7267|本田技研工業|輸送用機器|https://global.honda/jp/
7201|日産自動車|輸送用機器|https://www.nissan-global.com/JP/
7270|SUBARU|輸送用機器|https://www.subaru.co.jp/
7261|マツダ|輸送用機器|https://www.mazda.com/ja/
7269|スズキ|輸送用機器|https://www.suzuki.co.jp/
7211|三菱自動車工業|輸送用機器|https://www.mitsubishi-motors.com/jp/
7272|ヤマハ発動機|輸送用機器|https://global.yamaha-motor.com/jp/
6758|ソニーグループ|電気機器|https://www.sony.com/ja/
6752|パナソニック ホールディングス|電気機器|https://holdings.panasonic/jp/
6501|日立製作所|電気機器|https://www.hitachi.co.jp/
6503|三菱電機|電気機器|https://www.mitsubishielectric.co.jp/
6702|富士通|電気機器|https://global.fujitsu/ja-jp
6701|日本電気|電気機器|https://jpn.nec.com/
7751|キヤノン|電気機器|https://canon.jp/
7731|ニコン|精密機器|https://www.jp.nikon.com/
7752|リコー|電気機器|https://jp.ricoh.com/
6861|キーエンス|電気機器|https://www.keyence.co.jp/
6981|村田製作所|電気機器|https://www.murata.com/ja-jp
6971|京セラ|電気機器|https://www.kyocera.co.jp/
6762|TDK|電気機器|https://www.tdk.com/ja/
6963|ローム|電気機器|https://www.rohm.co.jp/
6723|ルネサスエレクトロニクス|電気機器|https://www.renesas.com/jp/ja
8035|東京エレクトロン|電気機器|https://www.tel.co.jp/
6857|アドバンテスト|電気機器|https://www.advantest.com/ja/
7735|SCREENホールディングス|電気機器|https://www.screen.co.jp/
6146|ディスコ|機械|https://www.disco.co.jp/jp/
6920|レーザーテック|電気機器|https://www.lasertec.co.jp/
6367|ダイキン工業|機械|https://www.daikin.co.jp/
7011|三菱重工業|機械|https://www.mhi.com/jp/
7012|川崎重工業|輸送用機器|https://www.khi.co.jp/
7013|IHI|機械|https://www.ihi.co.jp/
6301|小松製作所|機械|https://www.komatsu.jp/ja
6326|クボタ|機械|https://www.kubota.co.jp/
6954|ファナック|電気機器|https://www.fanuc.co.jp/
6506|安川電機|電気機器|https://www.yaskawa.co.jp/
6594|ニデック|電気機器|https://www.nidec.com/jp/
6201|豊田自動織機|輸送用機器|https://www.toyota-industries.com/jp/
4063|信越化学工業|化学|https://www.shinetsu.co.jp/jp/
3407|旭化成|化学|https://www.asahi-kasei.com/jp/
3402|東レ|繊維製品|https://www.toray.co.jp/
3401|帝人|繊維製品|https://www.teijin.co.jp/
4188|三菱ケミカルグループ|化学|https://www.mcgc.com/
4005|住友化学|化学|https://www.sumitomo-chem.co.jp/
4183|三井化学|化学|https://jp.mitsuichemicals.com/
5201|AGC|ガラス・土石製品|https://www.agc.com/
5401|日本製鉄|鉄鋼|https://www.nipponsteel.com/
5411|JFEホールディングス|鉄鋼|https://www.jfe-holdings.co.jp/
5406|神戸製鋼所|鉄鋼|https://www.kobelco.co.jp/
5711|三菱マテリアル|非鉄金属|https://www.mmc.co.jp/
5713|住友金属鉱山|非鉄金属|https://www.smm.co.jp/
5020|ENEOSホールディングス|石油・石炭製品|https://www.hd.eneos.co.jp/
5019|出光興産|石油・石炭製品|https://www.idemitsu.com/jp/
1605|INPEX|鉱業|https://www.inpex.co.jp/
9101|日本郵船|海運業|https://www.nyk.com/
9104|商船三井|海運業|https://www.mol.co.jp/
9107|川崎汽船|海運業|https://www.kline.co.jp/
9020|東日本旅客鉄道|陸運業|https://www.jreast.co.jp/
9022|東海旅客鉄道|陸運業|https://jr-central.co.jp/
9021|西日本旅客鉄道|陸運業|https://www.westjr.co.jp/
9202|ANAホールディングス|空運業|https://www.ana.co.jp/group/
9201|日本航空|空運業|https://www.jal.com/ja/
9432|日本電信電話|情報・通信業|https://group.ntt/jp/
9433|KDDI|情報・通信業|https://www.kddi.com/
9984|ソフトバンクグループ|情報・通信業|https://group.softbank/
9434|ソフトバンク|情報・通信業|https://www.softbank.jp/corp/
4755|楽天グループ|サービス業|https://corp.rakuten.co.jp/
6098|リクルートホールディングス|サービス業|https://recruit-holdings.com/ja/
4751|サイバーエージェント|サービス業|https://www.cyberagent.co.jp/
3092|ZOZO|小売業|https://corp.zozo.com/
4385|メルカリ|情報・通信業|https://about.mercari.com/
7974|任天堂|その他製品|https://www.nintendo.co.jp/
7832|バンダイナムコホールディングス|その他製品|https://www.bandainamco.co.jp/
9697|カプコン|情報・通信業|https://www.capcom.co.jp/
9766|コナミグループ|情報・通信業|https://www.konami.com/games/corporate/ja/
9684|スクウェア・エニックス・ホールディングス|情報・通信業|https://www.hd.square-enix.com/jpn/
6460|セガサミーホールディングス|機械|https://www.segasammy.co.jp/ja/
4911|資生堂|化学|https://corp.shiseido.com/jp/
4452|花王|化学|https://www.kao.com/jp/
8113|ユニ・チャーム|化学|https://www.unicharm.co.jp/ja/home.html
4912|ライオン|化学|https://www.lion.co.jp/ja/
2802|味の素|食料品|https://www.ajinomoto.co.jp/
2801|キッコーマン|食料品|https://www.kikkoman.co.jp/
2503|キリンホールディングス|食料品|https://www.kirinholdings.com/jp/
2502|アサヒグループホールディングス|食料品|https://www.asahigroup-holdings.com/
2501|サッポロホールディングス|食料品|https://www.sapporoholdings.jp/
2269|明治ホールディングス|食料品|https://www.meiji.com/
2897|日清食品ホールディングス|食料品|https://www.nissin.com/jp/
3382|セブン＆アイ・ホールディングス|小売業|https://www.7andi.com/
8267|イオン|小売業|https://www.aeon.info/
9983|ファーストリテイリング|小売業|https://www.fastretailing.com/jp/
7532|パン・パシフィック・インターナショナルホールディングス|小売業|https://ppih.co.jp/
8306|三菱UFJフィナンシャル・グループ|銀行業|https://www.mufg.jp/
8316|三井住友フィナンシャルグループ|銀行業|https://www.smfg.co.jp/
8411|みずほフィナンシャルグループ|銀行業|https://www.mizuho-fg.co.jp/
8591|オリックス|その他金融業|https://www.orix.co.jp/grp/
8766|東京海上ホールディングス|保険業|https://www.tokiomarinehd.com/
8750|第一生命ホールディングス|保険業|https://www.dai-ichi-life-hd.com/
8604|野村ホールディングス|証券・商品先物取引業|https://www.nomuraholdings.com/jp/
8601|大和証券グループ本社|証券・商品先物取引業|https://www.daiwa-grp.jp/
7202|いすゞ自動車|輸送用機器|https://www.isuzu.co.jp/
7205|日野自動車|輸送用機器|https://www.hino.co.jp/
6902|デンソー|輸送用機器|https://www.denso.com/jp/ja/
7259|アイシン|輸送用機器|https://www.aisin.com/jp/
3116|トヨタ紡織|輸送用機器|https://www.toyota-boshoku.com/jp/
7276|小糸製作所|電気機器|https://www.koito.co.jp/
7282|豊田合成|輸送用機器|https://www.toyoda-gosei.co.jp/
6995|東海理化電機製作所|輸送用機器|https://www.tokai-rika.co.jp/
7240|NOK|輸送用機器|https://www.nok.co.jp/
7242|カヤバ|輸送用機器|https://www.kyb.co.jp/
6584|三櫻工業|輸送用機器|https://www.sanoh.com/ja/
7296|エフ・シー・シー|輸送用機器|https://www.fcc-net.co.jp/
7231|トピー工業|輸送用機器|https://www.topy.co.jp/
5949|ユニプレス|輸送用機器|https://www.unipres.co.jp/
7105|三菱ロジスネクスト|輸送用機器|https://www.logisnext.com/
7278|エクセディ|輸送用機器|https://www.exedy.com/ja/
7283|愛三工業|輸送用機器|https://www.aisan-ind.co.jp/
7246|プレス工業|輸送用機器|https://www.presskogyo.co.jp/
7250|太平洋工業|輸送用機器|https://www.pacific-ind.co.jp/
7291|日本プラスト|輸送用機器|https://www.n-plast.co.jp/
7309|シマノ|輸送用機器|https://www.shimano.com/jp/
7220|武蔵精密工業|輸送用機器|https://www.musashi.co.jp/
7212|エフテック|輸送用機器|https://www.ftech.co.jp/
7214|GMB|輸送用機器|https://www.gmb.jp/
7313|テイ・エス テック|輸送用機器|https://www.tstech.co.jp/
7317|松屋アールアンドディ|輸送用機器|https://www.matsuyarandd.co.jp/
6504|富士電機|電気機器|https://www.fujielectric.co.jp/
6508|明電舎|電気機器|https://www.meidensha.co.jp/
6645|オムロン|電気機器|https://www.omron.com/jp/ja/
6841|横河電機|電気機器|https://www.yokogawa.co.jp/
6479|ミネベアミツミ|電気機器|https://www.minebeamitsumi.com/
6770|アルプスアルパイン|電気機器|https://www.alpsalpine.com/j/
6988|日東電工|化学|https://www.nitto.com/jp/ja/
6674|ジーエス・ユアサ コーポレーション|電気機器|https://www.gs-yuasa.com/jp/
6965|浜松ホトニクス|電気機器|https://www.hamamatsu.com/jp/ja.html
6856|堀場製作所|電気機器|https://www.horiba.com/jpn/
6845|アズビル|電気機器|https://www.azbil.com/jp/
6724|セイコーエプソン|電気機器|https://corporate.epson/ja/
4902|コニカミノルタ|電気機器|https://www.konicaminolta.com/jp-ja/
6753|シャープ|電気機器|https://corporate.jp.sharp/
6754|アンリツ|電気機器|https://www.anritsu.com/ja-jp/
6806|ヒロセ電機|電気機器|https://www.hirose.com/corporate/ja/
6807|日本航空電子工業|電気機器|https://www.jae.com/
6923|スタンレー電気|電気機器|https://www.stanley.co.jp/
6952|カシオ計算機|電気機器|https://www.casio.co.jp/
7732|トプコン|精密機器|https://www.topcon.co.jp/
7741|HOYA|精密機器|https://www.hoya.com/
4543|テルモ|精密機器|https://www.terumo.co.jp/
7701|島津製作所|精密機器|https://www.shimadzu.co.jp/
7716|ナカニシ|精密機器|https://www.nsk-nakanishi.co.jp/
7747|朝日インテック|精密機器|https://www.asahi-intecc.co.jp/
7762|シチズン時計|精密機器|https://www.citizen.co.jp/
8050|セイコーグループ|精密機器|https://www.seiko.co.jp/
7729|東京精密|精密機器|https://www.accretech.jp/
7740|タムロン|精密機器|https://www.tamron.com/jp/
7744|ノーリツ鋼機|精密機器|https://www.noritsu.co.jp/
6871|日本マイクロニクス|電気機器|https://www.mjc.co.jp/
6728|アルバック|電気機器|https://www.ulvac.co.jp/
6966|三井ハイテック|電気機器|https://www.mitsui-high-tec.com/ja/
6890|フェローテックホールディングス|電気機器|https://www.ferrotec.co.jp/
6525|KOKUSAI ELECTRIC|電気機器|https://www.kokusai-electric.com/
6526|ソシオネクスト|電気機器|https://www.socionext.com/jp/
3132|マクニカホールディングス|卸売業|https://holdings.macnica.co.jp/
8154|加賀電子|卸売業|https://www.taxan.co.jp/
2760|東京エレクトロン デバイス|卸売業|https://www.teldevice.co.jp/
7537|丸文|卸売業|https://www.marubun.co.jp/
6302|住友重機械工業|機械|https://www.shi.co.jp/
6305|日立建機|機械|https://www.hitachicm.com/global/ja/
6361|荏原製作所|機械|https://www.ebara.co.jp/
6315|TOWA|機械|https://www.towajapan.co.jp/
6324|ハーモニック・ドライブ・システムズ|機械|https://www.hds.co.jp/
6330|東洋エンジニアリング|建設業|https://www.toyo-eng.com/jp/ja/
6366|千代田化工建設|建設業|https://www.chiyodacorp.com/jp/
6368|オルガノ|機械|https://www.organo.co.jp/
6370|栗田工業|機械|https://www.kurita-water.com/
6371|椿本チエイン|機械|https://www.tsubakimoto.jp/
6383|ダイフク|機械|https://www.daifuku.com/jp/
6395|タダノ|機械|https://www.tadano.co.jp/
6406|フジテック|機械|https://www.fujitec.co.jp/
6412|平和|機械|https://www.heiwanet.co.jp/
6436|アマノ|機械|https://www.amano.co.jp/
6448|ブラザー工業|電気機器|https://global.brother/ja-jp
6457|グローリー|機械|https://www.glory.co.jp/
6465|ホシザキ|機械|https://www.hoshizaki.co.jp/
6471|日本精工|機械|https://www.nsk.com/jp-ja/
6472|NTN|機械|https://www.ntn.co.jp/japan/
6473|ジェイテクト|機械|https://www.jtekt.co.jp/
6481|THK|機械|https://www.thk.com/jp/ja/
6498|キッツ|機械|https://www.kitz.co.jp/
6586|マキタ|機械|https://www.makita.co.jp/
6103|オークマ|機械|https://www.okuma.co.jp/
6113|アマダ|機械|https://www.amada.co.jp/ja/
6136|オーエスジー|機械|https://www.osg.co.jp/
6273|SMC|機械|https://www.smcworld.com/ja-jp/
6268|ナブテスコ|機械|https://www.nabtesco.com/
6282|オイレス工業|機械|https://www.oiles.co.jp/
6254|野村マイクロ・サイエンス|機械|https://www.nomura-nms.co.jp/
6266|タツモ|機械|https://www.tazmo.co.jp/
6278|ユニオンツール|機械|https://www.uniontool.co.jp/
6298|ワイエイシイホールディングス|機械|https://www.yac.co.jp/
6332|月島ホールディングス|機械|https://www.tsk-g.co.jp/
6333|帝国電機製作所|機械|https://www.teikokudenki.co.jp/
6349|小森コーポレーション|機械|https://www.komori.com/ja/jp/
6351|鶴見製作所|機械|https://www.tsurumipump.co.jp/
6376|日機装|精密機器|https://www.nikkiso.co.jp/
6407|CKD|機械|https://www.ckd.co.jp/
6417|SANKYO|機械|https://www.sankyo-fever.co.jp/
6463|TPR|機械|https://www.tpr.co.jp/
6474|不二越|機械|https://www.nachi-fujikoshi.co.jp/
6490|PILLAR|機械|https://www.pillar.co.jp/
7003|三井E&S|機械|https://www.mes.co.jp/
7004|カナデビア|機械|https://www.kanadevia.com/
7014|名村造船所|輸送用機器|https://www.namura.co.jp/
6013|タクマ|機械|https://www.takuma.co.jp/
5631|日本製鋼所|機械|https://www.jsw.co.jp/
5801|古河電気工業|非鉄金属|https://www.furukawa.co.jp/
5802|住友電気工業|非鉄金属|https://sumitomoelectric.com/jp/
5803|フジクラ|非鉄金属|https://www.fujikura.co.jp/
5706|三井金属鉱業|非鉄金属|https://www.mitsui-kinzoku.com/
5714|DOWAホールディングス|非鉄金属|https://www.dowa.co.jp/
5715|古河機械金属|非鉄金属|https://www.furukawakk.co.jp/
5741|UACJ|非鉄金属|https://www.uacj.co.jp/
5851|リョービ|非鉄金属|https://www.ryobi-group.co.jp/
5938|LIXIL|金属製品|https://www.lixil.com/jp/
5929|三和ホールディングス|金属製品|https://www.sanwa-hldgs.co.jp/
5947|リンナイ|金属製品|https://www.rinnai.co.jp/
3436|SUMCO|金属製品|https://www.sumcosi.com/
3433|トーカロ|金属製品|https://www.tocalo.co.jp/
3443|川田テクノロジーズ|金属製品|https://www.kawada.jp/
5444|大和工業|鉄鋼|https://www.yamatokogyo.co.jp/
5471|大同特殊鋼|鉄鋼|https://www.daido.co.jp/
5480|日本冶金工業|鉄鋼|https://www.nyk.co.jp/
5541|大平洋金属|鉄鋼|https://www.pacific-metals.co.jp/
5563|新日本電工|鉄鋼|https://www.nippondenko.co.jp/
4202|ダイセル|化学|https://www.daicel.com/
4203|住友ベークライト|化学|https://www.sumibe.co.jp/
4204|積水化学工業|化学|https://www.sekisui.co.jp/
4205|日本ゼオン|化学|https://www.zeon.co.jp/
4206|アイカ工業|化学|https://www.aica.co.jp/
4208|UBE|化学|https://www.ube.com/
4212|積水樹脂|化学|https://www.sekisuijushi.co.jp/
4272|日本化薬|化学|https://www.nipponkayaku.co.jp/
4041|日本曹達|化学|https://www.nippon-soda.co.jp/
4042|東ソー|化学|https://www.tosoh.co.jp/
4043|トクヤマ|化学|https://www.tokuyama.co.jp/
4044|セントラル硝子|化学|https://www.cgco.co.jp/
4114|日本触媒|化学|https://www.shokubai.co.jp/
4118|カネカ|化学|https://www.kaneka.co.jp/
4182|三菱ガス化学|化学|https://www.mgc.co.jp/
4186|東京応化工業|化学|https://www.tok.co.jp/
4187|大阪有機化学工業|化学|https://www.ooc.co.jp/
4401|ADEKA|化学|https://www.adeka.co.jp/
4403|日油|化学|https://www.nof.co.jp/
4612|日本ペイントホールディングス|化学|https://www.nipponpaint-holdings.com/
4613|関西ペイント|化学|https://www.kansai.co.jp/
4626|太陽ホールディングス|化学|https://www.taiyo-hd.co.jp/
4631|DIC|化学|https://www.dic-global.com/ja/
4634|artience|化学|https://www.artiencegroup.com/ja/
4967|小林製薬|化学|https://www.kobayashi.co.jp/
4971|メック|化学|https://www.mec-co.com/
4980|デクセリアルズ|化学|https://www.dexerials.jp/
4996|クミアイ化学工業|化学|https://www.kumiai-chem.co.jp/
5142|アキレス|化学|https://www.achilles.jp/
5101|横浜ゴム|ゴム製品|https://www.y-yokohama.com/
5105|TOYO TIRE|ゴム製品|https://www.toyotires.co.jp/
5108|ブリヂストン|ゴム製品|https://www.bridgestone.co.jp/
5110|住友ゴム工業|ゴム製品|https://www.srigroup.co.jp/
5202|日本板硝子|ガラス・土石製品|https://www.nsg.co.jp/
5208|有沢製作所|化学|https://www.arisawa.co.jp/
5214|日本電気硝子|ガラス・土石製品|https://www.neg.co.jp/
5232|住友大阪セメント|ガラス・土石製品|https://www.soc.co.jp/
5233|太平洋セメント|ガラス・土石製品|https://www.taiheiyo-cement.co.jp/
5301|東海カーボン|ガラス・土石製品|https://www.tokaicarbon.co.jp/
5302|日本カーボン|ガラス・土石製品|https://www.carbon.co.jp/
5332|TOTO|ガラス・土石製品|https://jp.toto.com/
5333|日本碍子|ガラス・土石製品|https://www.ngk.co.jp/
5334|日本特殊陶業|ガラス・土石製品|https://www.niterragroup.com/jp/
5393|ニチアス|ガラス・土石製品|https://www.nichias.co.jp/
3405|クラレ|化学|https://www.kuraray.co.jp/
3101|東洋紡|繊維製品|https://www.toyobo.co.jp/
3103|ユニチカ|繊維製品|https://www.unitika.co.jp/
3105|日清紡ホールディングス|電気機器|https://www.nisshinbo.co.jp/
3107|ダイワボウホールディングス|卸売業|https://www.daiwabo-holdings.com/
3591|ワコールホールディングス|繊維製品|https://www.wacoalholdings.jp/
3608|TSIホールディングス|繊維製品|https://www.tsi-holdings.com/
3612|ワールド|繊維製品|https://corp.world.co.jp/
3861|王子ホールディングス|パルプ・紙|https://www.ojiholdings.co.jp/
3863|日本製紙|パルプ・紙|https://www.nipponpapergroup.com/
3865|北越コーポレーション|パルプ・紙|https://www.hokuetsucorp.com/
3880|大王製紙|パルプ・紙|https://www.daio-paper.co.jp/
4151|協和キリン|医薬品|https://www.kyowakirin.co.jp/
4502|武田薬品工業|医薬品|https://www.takeda.com/ja-jp/
4503|アステラス製薬|医薬品|https://www.astellas.com/jp/
4506|住友ファーマ|医薬品|https://www.sumitomo-pharma.co.jp/
4507|塩野義製薬|医薬品|https://www.shionogi.com/jp/ja/
4516|日本新薬|医薬品|https://www.nippon-shinyaku.co.jp/
4519|中外製薬|医薬品|https://www.chugai-pharm.co.jp/
4521|科研製薬|医薬品|https://www.kaken.co.jp/
4523|エーザイ|医薬品|https://www.eisai.co.jp/
4527|ロート製薬|医薬品|https://www.rohto.co.jp/
4528|小野薬品工業|医薬品|https://www.ono-pharma.com/ja
4530|久光製薬|医薬品|https://www.hisamitsu.co.jp/
4534|持田製薬|医薬品|https://www.mochida.co.jp/
4536|参天製薬|医薬品|https://www.santen.com/ja/
4540|ツムラ|医薬品|https://www.tsumura.co.jp/
4544|H.U.グループホールディングス|サービス業|https://www.hugp.com/
4552|JCRファーマ|医薬品|https://www.jcrpharm.co.jp/
4553|東和薬品|医薬品|https://www.towayakuhin.co.jp/
4568|第一三共|医薬品|https://www.daiichisankyo.co.jp/
4578|大塚ホールディングス|医薬品|https://www.otsuka.com/jp/
4887|サワイグループホールディングス|医薬品|https://www.sawaigroup.holdings/
2267|ヤクルト本社|食料品|https://www.yakult.co.jp/
2002|日清製粉グループ本社|食料品|https://www.nisshin.com/
2004|昭和産業|食料品|https://www.showa-sangyo.co.jp/
2201|森永製菓|食料品|https://www.morinaga.co.jp/
2206|江崎グリコ|食料品|https://www.glico.com/jp/
2212|山崎製パン|食料品|https://www.yamazakipan.co.jp/
2222|寿スピリッツ|食料品|https://www.kotobukispirits.co.jp/
2229|カルビー|食料品|https://www.calbee.co.jp/
2264|森永乳業|食料品|https://www.morinagamilk.co.jp/
2282|日本ハム|食料品|https://www.nipponham.co.jp/
2288|丸大食品|食料品|https://www.marudai.jp/
2587|サントリー食品インターナショナル|食料品|https://www.suntory.co.jp/softdrink/
2593|伊藤園|食料品|https://www.itoen.co.jp/
2602|日清オイリオグループ|食料品|https://www.nisshin-oillio.com/
2607|不二製油グループ本社|食料品|https://www.fujioilholdings.com/
2613|J-オイルミルズ|食料品|https://www.j-oil.com/
2810|ハウス食品グループ本社|食料品|https://housefoods-group.com/
2811|カゴメ|食料品|https://www.kagome.co.jp/company/
2871|ニチレイ|食料品|https://www.nichirei.co.jp/
2875|東洋水産|食料品|https://www.maruchan.co.jp/
2914|日本たばこ産業|食料品|https://www.jti.co.jp/
2931|ユーグレナ|食料品|https://www.euglena.jp/
1332|ニッスイ|水産・農林業|https://www.nissui.co.jp/
1333|マルハニチロ|水産・農林業|https://www.maruha-nichiro.co.jp/
1377|サカタのタネ|水産・農林業|https://corporate.sakataseed.co.jp/
1414|ショーボンドホールディングス|建設業|https://www.sho-bondhd.jp/
1719|安藤・間|建設業|https://www.ad-hzm.co.jp/
1721|コムシスホールディングス|建設業|https://www.comsys-hd.co.jp/
1801|大成建設|建設業|https://www.taisei.co.jp/
1802|大林組|建設業|https://www.obayashi.co.jp/
1803|清水建設|建設業|https://www.shimz.co.jp/
1808|長谷工コーポレーション|建設業|https://www.haseko.co.jp/
1812|鹿島建設|建設業|https://www.kajima.co.jp/
1820|西松建設|建設業|https://www.nishimatsu.co.jp/
1833|奥村組|建設業|https://www.okumuragumi.co.jp/
1860|戸田建設|建設業|https://www.toda.co.jp/
1861|熊谷組|建設業|https://www.kumagaigumi.co.jp/
1878|大東建託|建設業|https://www.kentaku.co.jp/
1885|東亜建設工業|建設業|https://www.toa-const.co.jp/
1893|五洋建設|建設業|https://www.penta-ocean.co.jp/
1925|大和ハウス工業|建設業|https://www.daiwahouse.co.jp/
1928|積水ハウス|建設業|https://www.sekisuihouse.co.jp/
1942|関電工|建設業|https://www.kandenko.co.jp/
1944|きんでん|建設業|https://www.kinden.co.jp/
1951|エクシオグループ|建設業|https://www.exeo.co.jp/
1959|九電工|建設業|https://www.kyudenko.co.jp/
1963|日揮ホールディングス|建設業|https://www.jgc.com/jp/
1969|高砂熱学工業|建設業|https://www.tte-net.com/
1979|大氣社|建設業|https://www.taikisha.co.jp/
1980|ダイダン|建設業|https://www.daidan.co.jp/
3003|ヒューリック|不動産業|https://www.hulic.co.jp/
3231|野村不動産ホールディングス|不動産業|https://www.nomura-re-hd.co.jp/
3289|東急不動産ホールディングス|不動産業|https://www.tokyu-fudosan-hd.co.jp/
3291|飯田グループホールディングス|不動産業|https://www.ighd.co.jp/
3465|ケイアイスター不動産|不動産業|https://ki-group.co.jp/
8801|三井不動産|不動産業|https://www.mitsuifudosan.co.jp/
8802|三菱地所|不動産業|https://www.mec.co.jp/
8803|平和不動産|不動産業|https://www.heiwa-net.co.jp/
8830|住友不動産|不動産業|https://www.sumitomo-rd.co.jp/
8848|レオパレス21|不動産業|https://www.leopalace21.co.jp/
8876|リログループ|サービス業|https://www.relo.jp/
8905|イオンモール|不動産業|https://www.aeonmall.com/
8919|カチタス|不動産業|https://katitas.jp/
8934|サンフロンティア不動産|不動産業|https://www.sunfrt.co.jp/
8058|三菱商事|卸売業|https://www.mitsubishicorp.com/jp/ja/
8001|伊藤忠商事|卸売業|https://www.itochu.co.jp/ja/
8002|丸紅|卸売業|https://www.marubeni.com/jp/
8031|三井物産|卸売業|https://www.mitsui.com/jp/ja/
8053|住友商事|卸売業|https://www.sumitomocorp.com/ja/jp
2768|双日|卸売業|https://www.sojitz.com/jp/
8015|豊田通商|卸売業|https://www.toyota-tsusho.com/
7459|メディパルホールディングス|卸売業|https://www.medipal.co.jp/
8129|東邦ホールディングス|卸売業|https://www.tohohd.co.jp/
2784|アルフレッサ ホールディングス|卸売業|https://www.alfresa.com/
8078|阪和興業|卸売業|https://www.hanwa.co.jp/
8088|岩谷産業|卸売業|https://www.iwatani.co.jp/jpn/
8098|稲畑産業|卸売業|https://www.inabata.co.jp/
8012|長瀬産業|卸売業|https://www.nagase.co.jp/
8136|サンリオ|卸売業|https://corporate.sanrio.co.jp/
9831|ヤマダホールディングス|小売業|https://www.yamada-holdings.jp/
9843|ニトリホールディングス|小売業|https://www.nitorihd.co.jp/
7453|良品計画|小売業|https://www.ryohin-keikaku.jp/
3086|J.フロント リテイリング|小売業|https://www.j-front-retailing.com/
3099|三越伊勢丹ホールディングス|小売業|https://www.imhds.co.jp/
8233|高島屋|小売業|https://www.takashimaya.co.jp/corp/
8242|エイチ・ツー・オー リテイリング|小売業|https://www.h2o-retailing.co.jp/
8273|イズミ|小売業|https://www.izumi.co.jp/corp/
8282|ケーズホールディングス|小売業|https://www.ksdenki.co.jp/
3141|ウエルシアホールディングス|小売業|https://www.welcia.co.jp/
3148|クリエイトSDホールディングス|小売業|https://www.createsdhd.co.jp/
3349|コスモス薬品|小売業|https://www.cosmospc.co.jp/
3391|ツルハホールディングス|小売業|https://www.tsuruha-hd.com/
3549|クスリのアオキホールディングス|小売業|https://www.kusuri-aoki-hd.co.jp/
7649|スギホールディングス|小売業|https://www.sugi-hd.co.jp/
8227|しまむら|小売業|https://www.shimamura.gr.jp/
2670|エービーシー・マート|小売業|https://www.abc-mart.co.jp/
2685|アダストリア|小売業|https://www.adastria.co.jp/
2726|パルグループホールディングス|小売業|https://www.palgroup.holdings/
3048|ビックカメラ|小売業|https://www.biccamera.co.jp/
3050|DCMホールディングス|小売業|https://www.dcm-hldgs.co.jp/
3064|MonotaRO|小売業|https://corp.monotaro.com/
3197|すかいらーくホールディングス|小売業|https://corp.skylark.co.jp/
3563|FOOD & LIFE COMPANIES|小売業|https://www.food-and-life.co.jp/
7616|コロワイド|小売業|https://www.colowide.co.jp/
7581|サイゼリヤ|小売業|https://www.saizeriya.co.jp/
7550|ゼンショーホールディングス|小売業|https://www.zensho.co.jp/
8179|ロイヤルホールディングス|小売業|https://www.royal-holdings.co.jp/
9842|アークランズ|小売業|https://www.arclands.co.jp/
9956|バローホールディングス|小売業|https://valorholdings.co.jp/
8303|SBI新生銀行|銀行業|https://www.sbishinseibank.co.jp/
8304|あおぞら銀行|銀行業|https://www.aozorabank.co.jp/
8308|りそなホールディングス|銀行業|https://www.resona-gr.co.jp/
8309|三井住友トラストグループ|銀行業|https://www.smth.jp/
8331|千葉銀行|銀行業|https://www.chibabank.co.jp/
8354|ふくおかフィナンシャルグループ|銀行業|https://www.fukuoka-fg.com/
8359|八十二銀行|銀行業|https://www.82bank.co.jp/
8369|京都フィナンシャルグループ|銀行業|https://www.kyoto-fg.co.jp/
8377|ほくほくフィナンシャルグループ|銀行業|https://www.hokuhoku-fg.co.jp/
8410|セブン銀行|銀行業|https://www.sevenbank.co.jp/
5831|しずおかフィナンシャルグループ|銀行業|https://www.shizuoka-fg.co.jp/
5832|ちゅうぎんフィナンシャルグループ|銀行業|https://www.chugin-fg.co.jp/
5838|楽天銀行|銀行業|https://www.rakuten-bank.co.jp/
7186|コンコルディア・フィナンシャルグループ|銀行業|https://www.concordia-fg.jp/
7182|ゆうちょ銀行|銀行業|https://www.jp-bank.japanpost.jp/
7167|めぶきフィナンシャルグループ|銀行業|https://www.mebuki-fg.co.jp/
7180|九州フィナンシャルグループ|銀行業|https://www.kyushu-fg.co.jp/
7173|東京きらぼしフィナンシャルグループ|銀行業|https://www.tokyo-kiraboshifg.co.jp/
8473|SBIホールディングス|証券・商品先物取引業|https://www.sbigroup.co.jp/
8697|日本取引所グループ|その他金融業|https://www.jpx.co.jp/
8698|マネックスグループ|証券・商品先物取引業|https://www.monexgroup.jp/
8706|極東証券|証券・商品先物取引業|https://www.kyokuto-sec.co.jp/
8570|イオンフィナンシャルサービス|その他金融業|https://www.aeonfinancial.co.jp/
8572|アコム|その他金融業|https://www.acom.co.jp/corp/
8584|ジャックス|その他金融業|https://www.jaccs.co.jp/corporate/
8585|オリエントコーポレーション|その他金融業|https://www.orico.co.jp/company/
8253|クレディセゾン|その他金融業|https://corporate.saisoncard.co.jp/
8439|東京センチュリー|その他金融業|https://www.tokyocentury.co.jp/
8424|芙蓉総合リース|その他金融業|https://www.fgl.co.jp/
8425|みずほリース|その他金融業|https://www.mizuho-ls.co.jp/
8593|三菱HCキャピタル|その他金融業|https://www.mitsubishi-hc-capital.com/
8630|SOMPOホールディングス|保険業|https://www.sompo-hd.com/
8725|MS&ADインシュアランスグループホールディングス|保険業|https://www.ms-ad-hd.com/
8795|T&Dホールディングス|保険業|https://www.td-holdings.co.jp/
7181|かんぽ生命保険|保険業|https://www.jp-life.japanpost.jp/
9024|西武ホールディングス|陸運業|https://www.seibuholdings.co.jp/
9001|東武鉄道|陸運業|https://www.tobu.co.jp/
9005|東急|陸運業|https://www.tokyu.co.jp/
9007|小田急電鉄|陸運業|https://www.odakyu.jp/
9008|京王電鉄|陸運業|https://www.keio.co.jp/
9009|京成電鉄|陸運業|https://www.keisei.co.jp/
9041|近鉄グループホールディングス|陸運業|https://www.kintetsu-g-hd.co.jp/
9042|阪急阪神ホールディングス|陸運業|https://www.hankyu-hanshin.co.jp/
9044|南海電気鉄道|陸運業|https://www.nankai.co.jp/
9045|京阪ホールディングス|陸運業|https://www.keihan-holdings.co.jp/
9064|ヤマトホールディングス|陸運業|https://www.yamato-hd.co.jp/
9065|山九|陸運業|https://www.sankyu.co.jp/
9069|センコーグループホールディングス|陸運業|https://www.senkogrouphd.co.jp/
9076|セイノーホールディングス|陸運業|https://www.seino.co.jp/seino/shd/
9142|九州旅客鉄道|陸運業|https://www.jrkyushu.co.jp/
9143|SGホールディングス|陸運業|https://www.sg-hldgs.co.jp/
9147|NIPPON EXPRESSホールディングス|陸運業|https://www.nipponexpress-holdings.com/ja/
9301|三菱倉庫|倉庫・運輸関連業|https://www.mitsubishi-logistics.co.jp/
9302|三井倉庫ホールディングス|倉庫・運輸関連業|https://msh.mitsui-soko.com/
9303|住友倉庫|倉庫・運輸関連業|https://www.sumitomo-soko.co.jp/
9364|上組|倉庫・運輸関連業|https://www.kamigumi.co.jp/
9511|沖縄電力|電気・ガス業|https://www.okiden.co.jp/
9501|東京電力ホールディングス|電気・ガス業|https://www.tepco.co.jp/
9502|中部電力|電気・ガス業|https://www.chuden.co.jp/
9503|関西電力|電気・ガス業|https://www.kepco.co.jp/
9504|中国電力|電気・ガス業|https://www.energia.co.jp/
9505|北陸電力|電気・ガス業|https://www.rikuden.co.jp/
9506|東北電力|電気・ガス業|https://www.tohoku-epco.co.jp/
9507|四国電力|電気・ガス業|https://www.yonden.co.jp/
9508|九州電力|電気・ガス業|https://www.kyuden.co.jp/
9509|北海道電力|電気・ガス業|https://www.hepco.co.jp/
9513|電源開発|電気・ガス業|https://www.jpower.co.jp/
9531|東京ガス|電気・ガス業|https://www.tokyo-gas.co.jp/
9532|大阪ガス|電気・ガス業|https://www.daigasgroup.com/
9533|東邦ガス|電気・ガス業|https://www.tohogas.co.jp/
9536|西部ガスホールディングス|電気・ガス業|https://hd.saibugas.co.jp/
9435|光通信|情報・通信業|https://www.hikari.co.jp/
9449|GMOインターネットグループ|情報・通信業|https://www.gmo.jp/
3626|TIS|情報・通信業|https://www.tis.co.jp/
4307|野村総合研究所|情報・通信業|https://www.nri.com/jp/
4684|オービック|情報・通信業|https://www.obic.co.jp/
4768|大塚商会|情報・通信業|https://www.otsuka-shokai.co.jp/corporate/
9719|SCSK|情報・通信業|https://www.scsk.jp/
2327|日鉄ソリューションズ|情報・通信業|https://www.nssol.nipponsteel.com/
3774|インターネットイニシアティブ|情報・通信業|https://www.iij.ad.jp/
543A|アークション|建設業|https://www.archion.co.jp/
285A|キオクシアホールディングス|電気機器|https://www.kioxia-holdings.com/ja-jp/
4061|デンカ|化学|https://www.denka.co.jp/
4901|富士フイルムホールディングス|化学|https://holdings.fujifilm.com/ja
4021|日産化学|化学|https://www.nissanchem.co.jp/
4004|レゾナック・ホールディングス|化学|https://www.resonac.com/jp/
6976|太陽誘電|電気機器|https://www.yuden.co.jp/jp/
7733|オリンパス|精密機器|https://www.olympus.co.jp/
8804|東京建物|不動産業|https://tatemono.com/
8252|丸井グループ|小売業|https://www.0101maruigroup.co.jp/
2432|ディー・エヌ・エー|サービス業|https://dena.com/jp/
3659|ネクソン|情報・通信業|https://www.nexon.co.jp/
4704|トレンドマイクロ|情報・通信業|https://www.trendmicro.com/ja_jp/
6178|日本郵政|サービス業|https://www.japanpost.jp/
4812|電通総研|情報・通信業|https://www.dentsusoken.com/
4825|ウェザーニューズ|情報・通信業|https://jp.weathernews.com/
9928|ミロク情報サービス|情報・通信業|https://www.mjs.co.jp/
2326|デジタルアーツ|情報・通信業|https://www.daj.jp/company/
3769|GMOペイメントゲートウェイ|情報・通信業|https://www.gmo-pg.com/
3844|コムチュア|情報・通信業|https://www.comture.com/
3923|ラクス|情報・通信業|https://www.rakus.co.jp/
3932|アカツキ|情報・通信業|https://aktsk.jp/
3994|マネーフォワード|情報・通信業|https://corp.moneyforward.com/
3993|PKSHA Technology|情報・通信業|https://www.pkshatech.com/
4051|GMOフィナンシャルゲート|情報・通信業|https://gmo-fg.com/
4373|シンプレクス・ホールディングス|情報・通信業|https://www.simplex.holdings/
4432|ウイングアーク1st|情報・通信業|https://corp.wingarc.com/
4478|フリー|情報・通信業|https://corp.freee.co.jp/
4483|JMDC|情報・通信業|https://www.jmdc.co.jp/
4689|LINEヤフー|情報・通信業|https://www.lycorp.co.jp/ja/
4661|オリエンタルランド|サービス業|https://www.olc.co.jp/ja/
4666|パーク24|不動産業|https://www.park24.co.jp/
4676|フジ・メディア・ホールディングス|情報・通信業|https://www.fujimediahd.co.jp/
4680|ラウンドワン|サービス業|https://www.round1-group.co.jp/
9401|TBSホールディングス|情報・通信業|https://www.tbsholdings.co.jp/
9404|日本テレビホールディングス|情報・通信業|https://www.ntvhd.co.jp/
9409|テレビ朝日ホールディングス|情報・通信業|https://www.tv-asahihd.co.jp/
9413|テレビ東京ホールディングス|情報・通信業|https://www.txhd.co.jp/
4324|電通グループ|サービス業|https://www.group.dentsu.com/jp/
2433|博報堂DYホールディングス|サービス業|https://www.hakuhodody-holdings.co.jp/
2371|カカクコム|サービス業|https://corporate.kakaku.com/
2127|日本M&Aセンターホールディングス|サービス業|https://www.nihon-ma.co.jp/groups/
2146|UTグループ|サービス業|https://www.ut-g.co.jp/
2154|オープンアップグループ|サービス業|https://www.openupgroup.co.jp/
2168|パソナグループ|サービス業|https://www.pasonagroup.co.jp/
2181|パーソルホールディングス|サービス業|https://www.persol-group.co.jp/
2413|エムスリー|サービス業|https://corporate.m3.com/
2471|エスプール|サービス業|https://www.spool.co.jp/
2492|インフォマート|サービス業|https://corp.infomart.co.jp/
6036|KeePer技研|サービス業|https://keepergiken.co.jp/
6080|M&Aキャピタルパートナーズ|サービス業|https://www.ma-cp.com/
6197|ソラスト|サービス業|https://www.solasto.co.jp/
6532|ベイカレント|サービス業|https://www.baycurrent.co.jp/
6533|Orchestra Holdings|サービス業|https://orchestra-hd.co.jp/
6544|ジャパンエレベーターサービスホールディングス|サービス業|https://www.jes24.co.jp/
6571|キュービーネットホールディングス|サービス業|https://www.qbnet.jp/
9602|東宝|情報・通信業|https://www.toho.co.jp/
9603|エイチ・アイ・エス|サービス業|https://www.his.co.jp/
9605|東映|情報・通信業|https://www.toei.co.jp/company/
9722|藤田観光|サービス業|https://www.fujita-kanko.co.jp/
9735|セコム|サービス業|https://www.secom.co.jp/
9744|メイテックグループホールディングス|サービス業|https://www.meitecgroup-holdings.com/
7984|コクヨ|その他製品|https://www.kokuyo.co.jp/
7911|TOPPANホールディングス|その他製品|https://www.holdings.toppan.com/ja/
7912|大日本印刷|その他製品|https://www.dnp.co.jp/
7936|アシックス|その他製品|https://corp.asics.com/jp/
7951|ヤマハ|その他製品|https://www.yamaha.com/ja/
7956|ピジョン|その他製品|https://www.pigeon.co.jp/
7966|リンテック|その他製品|https://www.lintec-global.com/
7976|三菱鉛筆|その他製品|https://www.mpuni.co.jp/
7988|ニフコ|化学|https://www.nifco.com/
8022|美津濃|その他製品|https://corp.mizuno.com/jp/
7867|タカラトミー|その他製品|https://www.takaratomy.co.jp/
7846|パイロットコーポレーション|その他製品|https://www.pilot.co.jp/
7803|ブシロード|その他製品|https://bushiroad.co.jp/
4922|コーセー|化学|https://corp.kose.co.jp/
4927|ポーラ・オルビスホールディングス|化学|https://www.po-holdings.co.jp/
4931|新日本製薬|化学|https://corporate.shinnihonseiyaku.co.jp/
4936|アクシージア|化学|https://axxzia.co.jp/
4928|ノエビアホールディングス|化学|https://www.noevirholdings.co.jp/
1417|ミライト・ワン|建設業|https://www.mirait-one.com/
1720|東急建設|建設業|https://www.tokyu-cnst.co.jp/
1726|ビーアールホールディングス|建設業|https://www.brhd.co.jp/
1762|高松コンストラクショングループ|建設業|https://www.takamatsu-cg.co.jp/
1775|富士古河E&C|建設業|https://www.ffec.co.jp/
1786|オリエンタル白石|建設業|https://www.orsc.co.jp/
1813|不動テトラ|建設業|https://www.fudotetra.co.jp/
1814|大末建設|建設業|https://www.daisue.co.jp/
1821|三井住友建設|建設業|https://www.smcon.co.jp/
1822|大豊建設|建設業|https://www.daiho.co.jp/
1835|東鉄工業|建設業|https://www.totetsu.co.jp/
1847|イチケン|建設業|https://www.ichiken.co.jp/
1852|淺沼組|建設業|https://www.asanuma.co.jp/
1866|北野建設|建設業|https://www.kitano.co.jp/
1870|矢作建設工業|建設業|https://www.yahagi.co.jp/
1871|ピーエス・コンストラクション|建設業|https://www.psc.co.jp/
1879|新日本建設|建設業|https://www.shinnihon-c.co.jp/
1882|東亜道路工業|建設業|https://www.toadoro.co.jp/
1884|日本道路|建設業|https://www.nipponroad.co.jp/
1887|日本国土開発|建設業|https://www.n-kokudo.co.jp/
1890|東洋建設|建設業|https://www.toyo-const.co.jp/
1898|世紀東急工業|建設業|https://www.seikitokyu.co.jp/
1911|住友林業|建設業|https://sfc.jp/information/company/
1926|ライト工業|建設業|https://www.raito.co.jp/
1934|ユアテック|建設業|https://www.yurtec.co.jp/
1939|四電工|建設業|https://www.yondenko.co.jp/
1941|中電工|建設業|https://www.chudenko.co.jp/
1945|東京エネシス|建設業|https://www.qtes.co.jp/
1946|トーエネック|建設業|https://www.toenec.co.jp/
1950|日本電設工業|建設業|https://www.densetsuko.co.jp/
1961|三機工業|建設業|https://www.sanki.co.jp/
1964|中外炉工業|建設業|https://chugai.co.jp/
1975|朝日工業社|建設業|https://www.asahikogyosha.co.jp/
1976|明星工業|建設業|https://www.meisei-kogyo.co.jp/
197A|タウンズ|医薬品|https://www.tauns.co.jp/
2998|クリアル|不動産業|https://corp.creal.jp/
2975|スター・マイカ・ホールディングス|不動産業|https://www.starmica-holdings.co.jp/
2980|SREホールディングス|不動産業|https://sre-group.co.jp/
2982|ADワークスグループ|不動産業|https://www.adwg.co.jp/
2986|LAホールディングス|不動産業|https://www.lahd.co.jp/
3232|三重交通グループホールディングス|不動産業|https://holdings.sanco.co.jp/
3244|サムティ|不動産業|https://www.samty.co.jp/
3252|地主|不動産業|https://www.jinushi-jp.com/
3276|JPMC|不動産業|https://www.jpmc.jp/
3284|フージャースホールディングス|不動産業|https://www.hoosiers.co.jp/
3288|オープンハウスグループ|不動産業|https://openhouse-group.co.jp/
3299|ムゲンエステート|不動産業|https://www.mugen-estate.co.jp/
3452|ビーロット|不動産業|https://www.b-lot.co.jp/
3457|And Doホールディングス|不動産業|https://www.housedo.co.jp/and-do/
3475|グッドコムアセット|不動産業|https://www.goodcomasset.co.jp/
3480|ジェイ・エス・ビー|不動産業|https://www.jsb.co.jp/
3482|ロードスターキャピタル|不動産業|https://loadstarcapital.com/
3491|GA technologies|不動産業|https://www.ga-tech.co.jp/
3496|アズーム|不動産業|https://azoom.jp/
3498|霞ヶ関キャピタル|不動産業|https://kasumigaseki.co.jp/
3479|ティーケーピー|不動産業|https://www.tkp.jp/
8841|テーオーシー|不動産業|https://www.toc.co.jp/
8844|コスモスイニシア|不動産業|https://www.cigr.co.jp/
8850|スターツコーポレーション|不動産業|https://www.starts.co.jp/
8860|フジ住宅|不動産業|https://www.fuji-jutaku.co.jp/
8877|エスリード|不動産業|https://www.eslead.co.jp/
8892|日本エスコン|不動産業|https://www.es-conjapan.co.jp/
8923|トーセイ|不動産業|https://www.toseicorp.co.jp/
8935|FJネクストホールディングス|不動産業|https://www.fjnext-hd.co.jp/
8940|インテリックス|不動産業|https://www.intellex.co.jp/
8944|ランドビジネス|不動産業|https://www.lbca.co.jp/
2353|日本駐車場開発|不動産業|https://www.n-p-d.co.jp/
2337|いちご|不動産業|https://www.ichigo.gr.jp/
3267|フィル・カンパニー|建設業|https://philcompany.jp/
2791|大黒天物産|小売業|https://www.e-dkt.co.jp/
2659|サンエー|小売業|https://www.san-a.co.jp/
2664|カワチ薬品|小売業|https://www.cawachi.co.jp/
2674|ハードオフコーポレーション|小売業|https://www.hardoff.co.jp/
2681|ゲオホールディングス|小売業|https://www.geonet.co.jp/
2686|ジーフット|小売業|https://www.g-foot.co.jp/
2695|くら寿司|小売業|https://www.kurasushi.co.jp/company/
2730|エディオン|小売業|https://www.edion.co.jp/
2742|ハローズ|小売業|https://www.halows.com/
2752|フジオフードグループ本社|小売業|https://www.fujiofood.com/
3028|アルペン|小売業|https://store.alpen-group.jp/corporate/
3034|クオールホールディングス|小売業|https://www.qolhd.co.jp/
3038|神戸物産|卸売業|https://www.gyomusuper.jp/company/
3053|ペッパーフードサービス|小売業|https://www.pepper-fs.co.jp/
3073|DDグループ|小売業|https://www.dd-grp.com/
3076|あい ホールディングス|卸売業|https://www.aiholdings.co.jp/
3087|ドトール・日レスホールディングス|小売業|https://www.dnh.co.jp/
3091|ブロンコビリー|小売業|https://www.bronco.co.jp/corporate/
3097|物語コーポレーション|小売業|https://www.monogatari.co.jp/
3134|Hamee|小売業|https://hamee.co.jp/
3179|シュッピン|小売業|https://www.syuppin.co.jp/
3182|オイシックス・ラ・大地|小売業|https://www.oisixradaichi.co.jp/
3191|ジョイフル本田|小売業|https://www.joyfulhonda.info/
3193|エターナルホスピタリティグループ|小売業|https://eternal-hospitality.co.jp/
3196|ホットランドホールディングス|小売業|https://www.hotland.co.jp/
3222|ユナイテッド・スーパーマーケット・ホールディングス|小売業|https://www.usmh.co.jp/
3319|ゴルフダイジェスト・オンライン|小売業|https://company.golfdigest.co.jp/
3333|あさひ|小売業|https://corporate.cb-asahi.co.jp/
3360|シップヘルスケアホールディングス|卸売業|https://www.shiphd.co.jp/
3387|クリエイト・レストランツ・ホールディングス|小売業|https://www.createrestaurants.com/
3395|サンマルクホールディングス|小売業|https://www.saint-marc-hd.com/
3539|JMホールディングス|小売業|https://www.jm-holdings.co.jp/
3543|コメダホールディングス|卸売業|https://www.komeda-holdings.co.jp/
3548|バロックジャパンリミテッド|小売業|https://www.baroque-global.com/
3558|ジェイドグループ|小売業|https://jade-group.jp/
3569|セーレン|繊維製品|https://www.seiren.com/
3611|マツオカコーポレーション|繊維製品|https://www.matuoka.co.jp/
7419|ノジマ|小売業|https://www.nojima.co.jp/
7421|カッパ・クリエイト|小売業|https://www.kappa-create.co.jp/
7451|三菱食品|卸売業|https://www.mitsubishi-shokuhin.com/
7467|萩原電気ホールディングス|卸売業|https://www.hagiwara.co.jp/
7476|アズワン|卸売業|https://www.as-1.co.jp/
7482|シモジマ|卸売業|https://www.shimojima.co.jp/
7504|高速|卸売業|https://www.kohsoku.com/
7513|コジマ|小売業|https://www.kojima.net/corporation/
7520|エコス|小売業|https://www.eco-s.co.jp/
7545|西松屋チェーン|小売業|https://www.24028.jp/
7593|VTホールディングス|小売業|https://www.vt-holdings.co.jp/
7606|ユナイテッドアローズ|小売業|https://www.united-arrows.co.jp/
7611|ハイデイ日高|小売業|https://hidakaya.hiday.co.jp/company/
7613|シークス|卸売業|https://www.siix.co.jp/
7630|壱番屋|小売業|https://www.ichibanya.co.jp/comp/
7646|PLANT|小売業|https://www.plant-co.jp/
7679|薬王堂ホールディングス|小売業|https://www.yakuodo-hd.co.jp/
7685|BuySell Technologies|卸売業|https://buysell-technologies.com/
8005|スクロール|小売業|https://www.scroll.jp/
8016|オンワードホールディングス|繊維製品|https://www.onward-hd.co.jp/
8020|兼松|卸売業|https://www.kanematsu.co.jp/
8029|ルックホールディングス|繊維製品|https://www.look-holdings.jp/
8032|日本紙パルプ商事|卸売業|https://www.kamipa.co.jp/
8043|スターゼン|卸売業|https://www.starzen.co.jp/
8051|山善|卸売業|https://www.yamazen.co.jp/
8056|BIPROGY|情報・通信業|https://www.biprogy.com/
8074|ユアサ商事|卸売業|https://www.yuasa.co.jp/
8075|神鋼商事|卸売業|https://www.shinsho.co.jp/
8079|正栄食品工業|卸売業|https://www.shoeifoods.co.jp/
8081|カナデン|卸売業|https://www.kanaden.co.jp/
8091|ニチモウ|卸売業|https://www.nichimo.co.jp/
8101|GSIクレオス|卸売業|https://www.gsi.co.jp/
8111|ゴールドウイン|繊維製品|https://about.goldwin.co.jp/
8114|デサント|繊維製品|https://www.descente.co.jp/
8125|ワキタ|卸売業|https://www.wakita.co.jp/
8130|サンゲツ|卸売業|https://www.sangetsu.co.jp/
8150|三信電気|卸売業|https://www.sanshin.co.jp/
8151|東陽テクニカ|卸売業|https://www.toyo.co.jp/
8153|モスフードサービス|卸売業|https://www.mos.co.jp/company/
8160|木曽路|小売業|https://www.kisoji.co.jp/
8163|SRSホールディングス|小売業|https://srs-holdings.co.jp/
8167|リテールパートナーズ|小売業|https://www.retailpartners.co.jp/
8182|いなげや|小売業|https://www.inageya.co.jp/
8194|ライフコーポレーション|小売業|https://www.lifecorp.jp/company/
8200|リンガーハット|小売業|https://www.ringerhut.co.jp/
8214|AOKIホールディングス|小売業|https://www.aoki-hd.co.jp/
8218|コメリ|小売業|https://www.komeri.bit.or.jp/company/
8237|松屋|小売業|https://www.matsuya.com/corp/
8244|近鉄百貨店|小売業|https://www.d-kintetsu.co.jp/corporate/
8276|平和堂|小売業|https://www.heiwado.jp/
8278|フジ|小売業|https://www.the-fuji.com/company/
8281|ゼビオホールディングス|小売業|https://www.xebio.co.jp/ja/
8283|PALTAC|卸売業|https://www.paltac.co.jp/
8285|三谷産業|卸売業|https://www.mitani.co.jp/
9267|Genky DrugStores|小売業|https://www.genky.co.jp/corporate/
9274|KPPグループホールディングス|卸売業|https://www.kpp-gr.com/
9279|ギフトホールディングス|小売業|https://www.gift-group.co.jp/
9824|泉州電業|卸売業|https://www.senden.co.jp/
9850|グルメ杵屋|小売業|https://www.gourmet-kineya-hd.co.jp/
9882|イエローハット|卸売業|https://www.yellowhat.jp/corp/
9900|サガミホールディングス|小売業|https://www.sagami-holdings.co.jp/
9948|アークス|小売業|https://www.arcs-g.co.jp/
9974|ベルク|小売業|https://www.belc.jp/company/
9990|サックスバー ホールディングス|小売業|https://www.sacs-bar.co.jp/
9997|ベルーナ|小売業|https://www.belluna.co.jp/
1375|雪国まいたけ|水産・農林業|https://www.maitake.co.jp/
1384|ホクリヨウ|水産・農林業|https://www.hokuryo.co.jp/
2001|ニップン|食料品|https://www.nippn.co.jp/
2108|日本甜菜製糖|食料品|https://www.nitten.co.jp/
2109|DM三井製糖ホールディングス|食料品|https://www.msdm-hd.com/
2117|ウェルネオシュガー|食料品|https://www.wellneo-sugar.co.jp/
2204|中村屋|食料品|https://www.nakamuraya.co.jp/
2207|名糖産業|食料品|https://www.meito-sangyo.co.jp/
2208|ブルボン|食料品|https://www.bourbon.co.jp/
2211|不二家|食料品|https://www.fujiya-peko.co.jp/
2217|モロゾフ|食料品|https://www.morozoff.co.jp/
2220|亀田製菓|食料品|https://www.kamedaseika.co.jp/
2266|六甲バター|食料品|https://www.qbb.co.jp/
2270|雪印メグミルク|食料品|https://www.meg-snow.com/
2281|プリマハム|食料品|https://www.primaham.co.jp/
2292|S Foods|食料品|https://www.sfoods.co.jp/
2296|伊藤ハム米久ホールディングス|食料品|https://www.itoham-yonekyu-holdings.com/
2531|宝ホールディングス|食料品|https://www.takara.co.jp/
2579|コカ・コーラ ボトラーズジャパンホールディングス|食料品|https://www.ccbj-holdings.com/
2585|ライフドリンク カンパニー|食料品|https://www.ld-company.com/
2590|ダイドーグループホールディングス|食料品|https://www.dydo-ghd.co.jp/
2612|かどや製油|食料品|https://www.kadoya.com/
2804|ブルドックソース|食料品|https://www.bulldog.co.jp/
2805|ヱスビー食品|食料品|https://www.sbfoods.co.jp/
2815|アリアケジャパン|食料品|https://www.ariakejapan.com/
2819|エバラ食品工業|食料品|https://www.ebarafoods.com/
2820|やまみ|食料品|https://www.yamami.co.jp/
2882|イートアンドホールディングス|食料品|https://www.eat-and.jp/
2884|ヨシムラ・フード・ホールディングス|食料品|https://www.y-food-h.com/
2908|フジッコ|食料品|https://www.fujicco.co.jp/
2910|ロック・フィールド|食料品|https://www.rockfield.co.jp/
2915|ケンコーマヨネーズ|食料品|https://www.kenkomayo.co.jp/
2918|わらべや日洋ホールディングス|食料品|https://www.warabeya.co.jp/
2922|なとり|食料品|https://www.natori.co.jp/
2929|ファーマフーズ|食料品|https://www.pharmafoods.co.jp/
2930|北の達人コーポレーション|化学|https://www.kitanotatsujin.com/
2935|ピックルスホールディングス|食料品|https://www.pickles-hd.co.jp/
2937|サンクゼール|食料品|https://www.stcousair.co.jp/
4551|鳥居薬品|医薬品|https://www.torii.co.jp/
4559|ゼリア新薬工業|医薬品|https://www.zeria.co.jp/
4565|ネクセラファーマ|医薬品|https://www.nxera.life/ja/
4569|杏林製薬|医薬品|https://www.kyorin-pharm.co.jp/
4587|ペプチドリーム|医薬品|https://www.peptidream.com/
4592|サンバイオ|医薬品|https://www.sanbio.com/
4593|ヘリオス|医薬品|https://www.healios.co.jp/
4880|セルソース|医薬品|https://www.cellsource.co.jp/
4886|あすか製薬ホールディングス|医薬品|https://www.aska-pharma-hd.co.jp/
4889|レナサイエンス|医薬品|https://www.renascience.co.jp/
4894|クオリプス|医薬品|https://cuorips.co.jp/
2395|新日本科学|サービス業|https://www.snbl.com/
2372|アイロムグループ|サービス業|https://www.iromgroup.co.jp/
2309|シミックホールディングス|サービス業|https://www.cmicgroup.com/
2301|学情|サービス業|https://company.gakujo.ne.jp/
2305|スタジオアリス|サービス業|https://www.studio-alice.co.jp/company/
2317|システナ|情報・通信業|https://www.systena.co.jp/
2331|ALSOK|サービス業|https://www.alsok.co.jp/
2378|ルネサンス|サービス業|https://www.s-renaissance.co.jp/
2384|SBSホールディングス|陸運業|https://www.sbs-group.co.jp/
2389|デジタルホールディングス|サービス業|https://digital-holdings.co.jp/
2391|プラネット|サービス業|https://www.planet-van.co.jp/
2429|ワールドホールディングス|サービス業|https://world-hd.co.jp/
2440|ぐるなび|サービス業|https://corporate.gnavi.co.jp/
2462|ライク|サービス業|https://www.like-gr.co.jp/
2469|ヒビノ|サービス業|https://www.hibino.co.jp/
2475|WDBホールディングス|サービス業|https://www.wdbhd.co.jp/
2489|アドウェイズ|サービス業|https://www.adways.net/
2491|バリューコマース|サービス業|https://www.valuecommerce.co.jp/
4290|プレステージ・インターナショナル|サービス業|https://www.prestigein.com/
4318|クイック|サービス業|https://919.jp/
4343|イオンファンタジー|サービス業|https://www.fantasy.co.jp/
4345|シーティーエス|サービス業|https://www.cts-h.co.jp/
4348|インフォコム|情報・通信業|https://www.infocom.co.jp/
4350|メディカルシステムネットワーク|小売業|https://www.msnw.co.jp/
4658|日本空調サービス|サービス業|https://www.nikku.co.jp/
4659|エイジス|サービス業|https://www.ajis-group.co.jp/
4665|ダスキン|サービス業|https://www.duskin.co.jp/
4694|ビー・エム・エル|サービス業|https://www.bml.co.jp/
4708|りらいあコミュニケーションズ|サービス業|https://www.relia-group.com/
4714|リソー教育|サービス業|https://www.riso-kyoikugroup.com/
4718|早稲田アカデミー|サービス業|https://www.waseda-ac.co.jp/corp/
4719|アルファシステムズ|情報・通信業|https://www.alpha.co.jp/
4732|ユー・エス・エス|サービス業|https://www.ussnet.co.jp/
4743|アイティフォー|情報・通信業|https://www.itfor.co.jp/
4754|トスネット|サービス業|https://www.tosnet.co.jp/
4763|クリーク・アンド・リバー社|サービス業|https://www.cri.co.jp/
4765|SBIグローバルアセットマネジメント|サービス業|https://www.sbiglobalam.co.jp/
4776|サイボウズ|情報・通信業|https://cybozu.co.jp/
4784|GMOインターネット|情報・通信業|https://internet.gmo/
4820|EMシステムズ|情報・通信業|https://emsystems.co.jp/
4826|CIJ|情報・通信業|https://www.cij.co.jp/
4839|WOWOW|情報・通信業|https://corporate.wowow.co.jp/
4845|スカラ|情報・通信業|https://scalagrp.jp/
4847|インテリジェント ウェイブ|情報・通信業|https://www.iwi.co.jp/
4848|フルキャストホールディングス|サービス業|https://www.fullcastholdings.co.jp/
6055|ジャパンマテリアル|サービス業|https://www.j-material.jp/
6058|ベクトル|サービス業|https://vectorinc.co.jp/
6062|チャーム・ケア・コーポレーション|サービス業|https://www.charmcc.jp/
6071|IBJ|サービス業|https://www.ibjapan.jp/
6078|バリューHR|サービス業|https://www.valuehr.com/
6088|シグマクシス・ホールディングス|サービス業|https://www.sigmaxyz.com/
6095|メドピア|サービス業|https://medpeer.co.jp/
6099|エラン|サービス業|https://www.kkelan.com/
6171|土木管理総合試験所|サービス業|https://www.dksiken.co.jp/
6183|ベルシステム24ホールディングス|サービス業|https://www.bell24.co.jp/ja/
6184|鎌倉新書|サービス業|https://www.kamakura-net.co.jp/
6185|SMN|サービス業|https://www.so-netmedia.jp/
6191|エアトリ|サービス業|https://www.airtrip.co.jp/
6194|アトラエ|サービス業|https://atrae.co.jp/
6196|ストライク|サービス業|https://www.strike.co.jp/
6200|インソース|サービス業|https://www.insource.co.jp/
6547|グリーンズ|サービス業|https://www.kk-greens.jp/
6551|ツナググループ・ホールディングス|サービス業|https://tghd.co.jp/
6560|エル・ティー・エス|サービス業|https://lt-s.jp/
6564|ミダックホールディングス|サービス業|https://www.midac.jp/
6569|日総工産|サービス業|https://www.nisso.co.jp/
6572|オープングループ|サービス業|https://open-group.co.jp/
7033|マネジメントソリューションズ|サービス業|https://www.msols.com/
7038|フロンティア・マネジメント|サービス業|https://www.frontier-mgmt.com/
7047|ポート|サービス業|https://www.theport.jp/
7059|コプロ・ホールディングス|サービス業|https://www.copro-h.co.jp/
7060|ギークス|サービス業|https://geechs.com/
7085|カーブスホールディングス|サービス業|https://www.curvesholdings.co.jp/
7095|Macbee Planet|サービス業|https://macbee-planet.com/
9216|ビーウィズ|サービス業|https://www.bewith.net/
9229|サンウェルズ|サービス業|https://sunwels.jp/
9246|プロジェクトホールディングス|サービス業|https://phd.co.jp/
9251|AB&Company|サービス業|https://ab-company.co.jp/
9270|バリュエンスホールディングス|卸売業|https://www.valuence.inc/
9551|メタウォーター|電気・ガス業|https://www.metawater.co.jp/
9621|建設技術研究所|サービス業|https://www.ctie.co.jp/
9622|スペース|サービス業|https://www.space-tokyo.co.jp/
9627|アインホールディングス|小売業|https://www.ainj.co.jp/
9632|スバル興業|サービス業|https://subaru-kougyou.jp/
9644|タナベコンサルティンググループ|サービス業|https://www.tanabeconsulting-group.com/
9658|ビジネスブレイン太田昭和|情報・通信業|https://www.bbs.co.jp/
9672|東京都競馬|サービス業|https://www.tokyotokeiba.co.jp/
9678|カナモト|サービス業|https://www.kanamoto.co.jp/
9682|DTS|情報・通信業|https://www.dts.co.jp/
9692|シーイーシー|情報・通信業|https://www.cec-ltd.co.jp/
9702|アイ・エス・ビー|情報・通信業|https://www.isb.co.jp/
9706|日本空港ビルデング|不動産業|https://www.tokyo-airport-bldg.co.jp/
9715|トランス・コスモス|サービス業|https://www.trans-cosmos.co.jp/
9716|乃村工藝社|サービス業|https://www.nomurakougei.co.jp/
9729|トーカイ|サービス業|https://www.tokai-corp.com/
9739|NSW|情報・通信業|https://www.nsw.co.jp/
9740|セントラル警備保障|サービス業|https://www.we-are-csp.co.jp/
9793|ダイセキ|サービス業|https://www.daiseki.co.jp/
9795|ステップ|サービス業|https://www.stepnet.co.jp/
9799|旭情報サービス|情報・通信業|https://www.aiskk.co.jp/
2121|MIXI|サービス業|https://mixi.co.jp/
2130|メンバーズ|サービス業|https://www.members.co.jp/
2138|クルーズ|情報・通信業|https://crooz.co.jp/
2150|ケアネット|サービス業|https://www.carenet.co.jp/
2157|コシダカホールディングス|サービス業|https://www.koshidakaholdings.co.jp/
2170|リンクアンドモチベーション|サービス業|https://www.lmi.ne.jp/
2175|エス・エム・エス|サービス業|https://www.bm-sms.co.jp/
2198|アイ・ケイ・ケイホールディングス|サービス業|https://www.ikk-grp.jp/
3632|グリー|情報・通信業|https://corp.gree.net/jp/ja/
3635|コーエーテクモホールディングス|情報・通信業|https://www.koeitecmo.co.jp/
3649|ファインデックス|情報・通信業|https://findex.co.jp/
3655|ブレインパッド|情報・通信業|https://www.brainpad.co.jp/
3660|アイスタイル|情報・通信業|https://www.istyle.co.jp/
3661|エムアップホールディングス|情報・通信業|https://m-upholdings.co.jp/
3662|エイチームホールディングス|情報・通信業|https://www.a-tm.co.jp/
3663|セルシス|情報・通信業|https://www.celsys.com/
3665|エニグモ|情報・通信業|https://enigmo.co.jp/
3668|コロプラ|情報・通信業|https://colopl.co.jp/
3673|ブロードリーフ|情報・通信業|https://www.broadleaf.co.jp/
3675|クロス・マーケティンググループ|情報・通信業|https://www.cm-group.co.jp/
3676|デジタルハーツホールディングス|情報・通信業|https://www.digitalhearts-hd.com/
3678|メディアドゥ|情報・通信業|https://mediado.jp/
3681|ブイキューブ|情報・通信業|https://jp.vcube.com/
3683|サイバーリンクス|情報・通信業|https://www.cyber-l.co.jp/
3687|フィックスターズ|情報・通信業|https://www.fixstars.com/ja/
3694|オプティム|情報・通信業|https://www.optim.co.jp/
3696|セレス|情報・通信業|https://ceres-inc.jp/
3738|ティーガイア|情報・通信業|https://www.t-gaia.co.jp/
3741|セック|情報・通信業|https://www.sec.co.jp/
3762|テクマトリックス|情報・通信業|https://www.techmatrix.co.jp/
3763|プロシップ|情報・通信業|https://www.proship.co.jp/
3765|ガンホー・オンライン・エンターテイメント|情報・通信業|https://www.gungho.co.jp/
3771|システムリサーチ|情報・通信業|https://www.sr-net.co.jp/
3793|ドリコム|情報・通信業|https://drecom.co.jp/
3804|システム ディ|情報・通信業|https://www.systemd.co.jp/
3834|朝日ネット|情報・通信業|https://asahi-net.co.jp/
3853|アステリア|情報・通信業|https://jp.asteria.com/
3900|クラウドワークス|情報・通信業|https://crowdworks.co.jp/
3901|マークラインズ|情報・通信業|https://www.marklines.com/ja/corporate/
3902|メディカル・データ・ビジョン|情報・通信業|https://www.mdv.co.jp/
3903|gumi|情報・通信業|https://gu3.co.jp/
3915|テラスカイ|情報・通信業|https://www.terrasky.co.jp/
3916|デジタル・インフォメーション・テクノロジー|情報・通信業|https://www.ditgroup.jp/
3918|PCIホールディングス|情報・通信業|https://www.pci-h.co.jp/
3921|ネオジャパン|情報・通信業|https://www.neo.co.jp/
3922|PR TIMES|情報・通信業|https://prtimes.co.jp/
3925|ダブルスタンダード|情報・通信業|https://double-std.com/
3937|Ubicomホールディングス|情報・通信業|https://www.ubicom-hd.com/
3962|チェンジホールディングス|情報・通信業|https://www.change-jp.com/
3963|シンクロ・フード|情報・通信業|https://www.synchro-food.co.jp/
3964|オークネット|情報・通信業|https://www.aucnet.co.jp/
3978|マクロミル|情報・通信業|https://www.macromill.com/
3983|オロ|情報・通信業|https://www.oro.com/ja/
3984|ユーザーローカル|情報・通信業|https://www.userlocal.jp/
3985|テモナ|情報・通信業|https://temona.co.jp/
3987|エコモット|情報・通信業|https://www.ecomott.co.jp/
4390|アイ・ピー・エス|情報・通信業|https://ipsism.co.jp/
4396|システムサポートホールディングス|情報・通信業|https://www.sts-hd.co.jp/
4397|チームスピリット|情報・通信業|https://corp.teamspirit.com/
4410|ハリマ化成グループ|化学|https://www.harima.co.jp/
4423|アルテリア・ネットワークス|情報・通信業|https://www.arteria-net.com/
4431|スマレジ|情報・通信業|https://corp.smaregi.jp/
4436|ミンカブ・ジ・インフォノイド|情報・通信業|https://minkabu.co.jp/
4443|Sansan|情報・通信業|https://jp.corp-sansan.com/
4446|Link-Uグループ|情報・通信業|https://www.link-u.group/
4449|ギフティ|情報・通信業|https://giftee.co.jp/
4480|メドレー|情報・通信業|https://www.medley.jp/
4493|サイバーセキュリティクラウド|情報・通信業|https://www.cscloud.co.jp/
4498|サイバートラスト|情報・通信業|https://www.cybertrust.co.jp/
4722|フューチャー|情報・通信業|https://www.future.co.jp/
4725|CAC Holdings|情報・通信業|https://www.cac-holdings.com/
4733|オービックビジネスコンサルタント|情報・通信業|https://www.obc.co.jp/
4746|東計電算|情報・通信業|https://www.toukei.co.jp/
4752|昭和システムエンジニアリング|情報・通信業|https://www.showa-sys-eng.co.jp/
4772|ストリームメディアコーポレーション|情報・通信業|https://www.streammedia.co.jp/
4813|ACCESS|情報・通信業|https://www.access-company.com/
4819|デジタルガレージ|情報・通信業|https://www.garage.co.jp/
4828|ビジネスエンジニアリング|情報・通信業|https://www.b-en-g.co.jp/
4832|JFEシステムズ|情報・通信業|https://www.jfe-systems.com/
4849|エン・ジャパン|サービス業|https://corp.en-japan.com/
5253|カバー|情報・通信業|https://cover-corp.com/
5254|Arent|情報・通信業|https://arent.co.jp/
5258|トランザクション・メディア・ネットワークス|情報・通信業|https://www.tm-nets.com/
5574|ABEJA|情報・通信業|https://www.abejainc.com/
5588|ファーストアカウンティング|情報・通信業|https://www.fastaccounting.jp/
5595|QPS研究所|情報・通信業|https://i-qps.net/
5578|ARアドバンストテクノロジ|情報・通信業|https://ari-jp.com/
5586|Laboro.AI|情報・通信業|https://laboro.ai/
5616|雨風太陽|情報・通信業|https://ame-kaze-taiyo.jp/
5618|ナイル|情報・通信業|https://nyle.co.jp/
5582|グリッド|情報・通信業|https://gridpredict.jp/
6521|オキサイド|電気機器|https://www.opt-oxide.com/
6590|芝浦メカトロニクス|電気機器|https://www.shibaura.co.jp/
6613|QDレーザ|電気機器|https://www.qdlaser.com/
6617|東光高岳|電気機器|https://www.tktk.co.jp/
6622|ダイヘン|電気機器|https://www.daihen.co.jp/
6627|テラプローブ|電気機器|https://www.teraprobe.com/
6630|ヤーマン|電気機器|https://www.ya-man.co.jp/
6632|JVCケンウッド|電気機器|https://www.jvckenwood.com/jp.html
6638|ミマキエンジニアリング|電気機器|https://ir.mimaki.com/
`.trim().split('\n').map(row=>{const [code,name,sector,url]=row.split('|');return {code,name,sector,url}});
