const companies=`
7203|トヨタ自動車|輸送用機器|https://global.toyota/jp/
7267|本田技研工業|輸送用機器|https://global.honda/jp/
7201|日産自動車|輸送用機器|https://www.nissan-global.com/JP/
7270|SUBARU|輸送用機器|https://www.subaru.co.jp/
7261|マツダ|輸送用機器|https://www.mazda.com/ja/
7269|スズキ|輸送用機器|https://www.suzuki.co.jp/
7211|三菱自動車工業|輸送用機器|https://www.mitsubishi-motors.com/jp/
7272|ヤマハ発動機|輸送用機器|https://global.yamaha-motor.com/jp/
6758|ソニーグループ|電気機器|https://www.sony.com/ja/
6752|パナソニック ホールディングス|電気機器|https://holdings.panasonic/jp/
6501|日立製作所|電気機器|https://www.hitachi.co.jp/
6503|三菱電機|電気機器|https://www.mitsubishielectric.co.jp/
6702|富士通|電気機器|https://global.fujitsu/ja-jp
6701|日本電気|電気機器|https://jpn.nec.com/
7751|キヤノン|電気機器|https://canon.jp/
7731|ニコン|精密機器|https://www.jp.nikon.com/
7752|リコー|電気機器|https://jp.ricoh.com/
6861|キーエンス|電気機器|https://www.keyence.co.jp/
6981|村田製作所|電気機器|https://www.murata.com/ja-jp
6971|京セラ|電気機器|https://www.kyocera.co.jp/
6762|TDK|電気機器|https://www.tdk.com/ja/
6963|ローム|電気機器|https://www.rohm.co.jp/
6723|ルネサスエレクトロニクス|電気機器|https://www.renesas.com/jp/ja
8035|東京エレクトロン|電気機器|https://www.tel.co.jp/
6857|アドバンテスト|電気機器|https://www.advantest.com/ja/
7735|SCREENホールディングス|電気機器|https://www.screen.co.jp/
6146|ディスコ|機械|https://www.disco.co.jp/jp/
6920|レーザーテック|電気機器|https://www.lasertec.co.jp/
6367|ダイキン工業|機械|https://www.daikin.co.jp/
7011|三菱重工業|機械|https://www.mhi.com/jp/
7012|川崎重工業|輸送用機器|https://www.khi.co.jp/
7013|IHI|機械|https://www.ihi.co.jp/
6301|小松製作所|機械|https://www.komatsu.jp/ja
6326|クボタ|機械|https://www.kubota.co.jp/
6954|ファナック|電気機器|https://www.fanuc.co.jp/
6506|安川電機|電気機器|https://www.yaskawa.co.jp/
6594|ニデック|電気機器|https://www.nidec.com/jp/
6201|豊田自動織機|輸送用機器|https://www.toyota-industries.com/jp/
4063|信越化学工業|化学|https://www.shinetsu.co.jp/jp/
3407|旭化成|化学|https://www.asahi-kasei.com/jp/
3402|東レ|繊維製品|https://www.toray.co.jp/
3401|帝人|繊維製品|https://www.teijin.co.jp/
4188|三菱ケミカルグループ|化学|https://www.mcgc.com/
4005|住友化学|化学|https://www.sumitomo-chem.co.jp/
4183|三井化学|化学|https://jp.mitsuichemicals.com/
5201|AGC|ガラス・土石製品|https://www.agc.com/
5401|日本製鉄|鉄鋼|https://www.nipponsteel.com/
5411|JFEホールディングス|鉄鋼|https://www.jfe-holdings.co.jp/
5406|神戸製鋼所|鉄鋼|https://www.kobelco.co.jp/
5711|三菱マテリアル|非鉄金属|https://www.mmc.co.jp/
5713|住友金属鉱山|非鉄金属|https://www.smm.co.jp/
5020|ENEOSホールディングス|石油・石炭製品|https://www.hd.eneos.co.jp/
5019|出光興産|石油・石炭製品|https://www.idemitsu.com/jp/
1605|INPEX|鉱業|https://www.inpex.co.jp/
9101|日本郵船|海運業|https://www.nyk.com/
9104|商船三井|海運業|https://www.mol.co.jp/
9107|川崎汽船|海運業|https://www.kline.co.jp/
9020|東日本旅客鉄道|陸運業|https://www.jreast.co.jp/
9022|東海旅客鉄道|陸運業|https://jr-central.co.jp/
9021|西日本旅客鉄道|陸運業|https://www.westjr.co.jp/
9202|ANAホールディングス|空運業|https://www.ana.co.jp/group/
9201|日本航空|空運業|https://www.jal.com/ja/
9432|日本電信電話|情報・通信業|https://group.ntt/jp/
9433|KDDI|情報・通信業|https://www.kddi.com/
9984|ソフトバンクグループ|情報・通信業|https://group.softbank/
9434|ソフトバンク|情報・通信業|https://www.softbank.jp/corp/
4755|楽天グループ|サービス業|https://corp.rakuten.co.jp/
6098|リクルートホールディングス|サービス業|https://recruit-holdings.com/ja/
4751|サイバーエージェント|サービス業|https://www.cyberagent.co.jp/
3092|ZOZO|小売業|https://corp.zozo.com/
4385|メルカリ|情報・通信業|https://about.mercari.com/
7974|任天堂|その他製品|https://www.nintendo.co.jp/
7832|バンダイナムコホールディングス|その他製品|https://www.bandainamco.co.jp/
9697|カプコン|情報・通信業|https://www.capcom.co.jp/
9766|コナミグループ|情報・通信業|https://www.konami.com/games/corporate/ja/
9684|スクウェア・エニックス・ホールディングス|情報・通信業|https://www.hd.square-enix.com/jpn/
6460|セガサミーホールディングス|機械|https://www.segasammy.co.jp/ja/
4911|資生堂|化学|https://corp.shiseido.com/jp/
4452|花王|化学|https://www.kao.com/jp/
8113|ユニ・チャーム|化学|https://www.unicharm.co.jp/ja/home.html
4912|ライオン|化学|https://www.lion.co.jp/ja/
2802|味の素|食料品|https://www.ajinomoto.co.jp/
2801|キッコーマン|食料品|https://www.kikkoman.co.jp/
2503|キリンホールディングス|食料品|https://www.kirinholdings.com/jp/
2502|アサヒグループホールディングス|食料品|https://www.asahigroup-holdings.com/
2501|サッポロホールディングス|食料品|https://www.sapporoholdings.jp/
2269|明治ホールディングス|食料品|https://www.meiji.com/
2897|日清食品ホールディングス|食料品|https://www.nissin.com/jp/
3382|セブン＆アイ・ホールディングス|小売業|https://www.7andi.com/
8267|イオン|小売業|https://www.aeon.info/
9983|ファーストリテイリング|小売業|https://www.fastretailing.com/jp/
7532|パン・パシフィック・インターナショナルホールディングス|小売業|https://ppih.co.jp/
8306|三菱UFJフィナンシャル・グループ|銀行業|https://www.mufg.jp/
8316|三井住友フィナンシャルグループ|銀行業|https://www.smfg.co.jp/
8411|みずほフィナンシャルグループ|銀行業|https://www.mizuho-fg.co.jp/
8591|オリックス|その他金融業|https://www.orix.co.jp/grp/
8766|東京海上ホールディングス|保険業|https://www.tokiomarinehd.com/
8750|第一生命ホールディングス|保険業|https://www.dai-ichi-life-hd.com/
8604|野村ホールディングス|証券・商品先物取引業|https://www.nomuraholdings.com/jp/
8601|大和証券グループ本社|証券・商品先物取引業|https://www.daiwa-grp.jp/
`.trim().split('\n').map(row=>{const [code,name,sector,url]=row.split('|');return {code,name,sector,url}});
